- hosts: "{{ host }}"
  gather_facts: no
  tasks:                # Defining tasks for the playbook
    - name: Destroy the vm '{{ vmname }}'
      virt:
        name: "{{ vmname }}"
        command: destroy
        state: destroyed
    - name: Undefine the vm '{{ vmname }}'
      virt:
        name: "{{ vmname }}"
        command: undefine
