- hosts: "{{ host }}"
  gather_facts: no
  tasks:                # Defining tasks for the playbook
    - name: Copying template file
      copy:
        src: "/var/lib/libvirt/images/template.img"
        dest: "/var/lib/libvirt/images/{{ vmname }}.img"
        remote_src: yes
    - name: Create the vm '{{ vmname }}'
      virt:
        name: "{{ vmname }}"
        command: define
        xml: '{{ lookup("template", "{{ xmlname }}") }}'
    - name: Start the vm '{{ vmname }}'
      virt:
        name: "{{ vmname }}"
        state: running
